// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourMoney.Infrastructure.Persistence;

#nullable disable

namespace YourMoney.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723125458_AddMetaMensalModalidade")]
    partial class AddMetaMensalModalidade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YourMoney.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoriaPaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoTransacao")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId")
                        .HasDatabaseName("IX_Categoria_CategoriaPaiId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbCategoria", (string)null);
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.ContaFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbContaFinanceira", (string)null);
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdContaFinanceira")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("NumeroParcela")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParcelamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TotalParcelas")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorTotalParcelamento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("IX_Despesa_IdCategoria");

                    b.HasIndex("IdContaFinanceira")
                        .HasDatabaseName("IX_Despesa_IdContaFinanceira");

                    b.HasIndex("ParcelamentoId")
                        .HasDatabaseName("IX_Despesa_ParcelamentoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ParcelamentoId", "NumeroParcela")
                        .HasDatabaseName("IX_Despesa_Parcelamento_Parcela");

                    b.ToTable("tbDespesa", (string)null);
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.DespesaRecorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("int");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdContaFinanceira")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNaturezaDespesa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdTipoDespesa")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria")
                        .HasDatabaseName("IX_DespesaRecorrente_IdCategoria");

                    b.HasIndex("IdContaFinanceira")
                        .HasDatabaseName("IX_DespesaRecorrente_IdContaFinanceira");

                    b.HasIndex("IdNaturezaDespesa")
                        .HasDatabaseName("IX_DespesaRecorrente_IdNaturezaDespesa");

                    b.HasIndex("IdTipoDespesa")
                        .HasDatabaseName("IX_DespesaRecorrente_IdTipoDespesa");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "Ativa")
                        .HasDatabaseName("IX_DespesaRecorrente_UsuarioId_Ativa");

                    b.HasIndex("UsuarioId", "DataInicio", "DataTermino")
                        .HasDatabaseName("IX_DespesaRecorrente_UsuarioId_Periodo");

                    b.ToTable("tbDespesaRecorrente", (string)null);
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.DespesaRecorrenteOcorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DespesaConfirmadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DespesaRecorrenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinalizadaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DespesaConfirmadaId")
                        .HasDatabaseName("IX_DespesaRecorrenteOcorrencia_DespesaConfirmadaId");

                    b.HasIndex("DespesaRecorrenteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "DespesaRecorrenteId", "MesReferencia")
                        .IsUnique()
                        .HasDatabaseName("UX_DespesaRecorrenteOcorrencia_Usuario_Recorrencia_Mes");

                    b.HasIndex("UsuarioId", "MesReferencia", "Status")
                        .HasDatabaseName("IX_DespesaRecorrenteOcorrencia_Usuario_Mes_Status");

                    b.ToTable("tbDespesaRecorrenteOcorrencia", (string)null);
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.Investimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataInvestimento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataResgate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("MesReferencia")
                        .HasColumnType("date")
                        .HasColumnName("mesReferencia");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("OperacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ReceitaRecorrenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataInvestimento")
                        .HasDatabaseName("IX_Investimento_Data");

                    b.HasIndex("MesReferencia")
                        .HasDatabaseName("IX_Investimento_MesReferencia");

                    b.HasIndex("ReceitaRecorrenteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "DataInvestimento")
                        .HasDatabaseName("IX_Investimento_UsuarioId_DataInvestimento");

                    b.HasIndex("UsuarioId", "OperacaoId")
                        .IsUnique()
                        .HasDatabaseName("UX_Investimento_UsuarioId_OperacaoId")
                        .HasFilter("[OperacaoId] IS NOT NULL");

                    b.HasIndex("UsuarioId", "ReceitaRecorrenteId")
                        .HasDatabaseName("IX_Investimento_UsuarioId_ReceitaRecorrenteId");

                    b.ToTable("tbInvestimento", (string)null);
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.Meta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataObjetivo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorObjetivo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DataObjetivo")
                        .HasDatabaseName("IX_Meta_DataObjetivo");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Meta_Status");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbMeta", (string)null);
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.MetaMensal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PercentualReceita")
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("TipoDefinicao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Percentual");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("ValorMeta")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "MesReferencia")
                        .HasDatabaseName("IX_MetaMensal_Usuario_MesReferencia");

                    b.ToTable("tbMetaMensal", null, t =>
                        {
                            t.HasCheckConstraint("CK_MetaMensal_Definicao", "([TipoDefinicao] = N'Percentual' AND [PercentualReceita] IS NOT NULL AND [PercentualReceita] > 0 AND [ValorMeta] IS NULL) OR ([TipoDefinicao] = N'Valor' AND [ValorMeta] IS NOT NULL AND [ValorMeta] > 0 AND [PercentualReceita] IS NULL)");
                        });
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.Receita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("DespesaVinculadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdContaFinanceira")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("MesReferencia")
                        .HasColumnType("date")
                        .HasColumnName("mesReferencia");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("RendaDisponivel");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DespesaVinculadaId")
                        .HasDatabaseName("IX_Receita_DespesaVinculadaId");

                    b.HasIndex("IdContaFinanceira")
                        .HasDatabaseName("IX_Receita_IdContaFinanceira");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "Natureza", "MesReferencia")
                        .HasDatabaseName("IX_Receita_Usuario_Natureza_MesReferencia");

                    b.ToTable("tbReceita", (string)null);
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.ReceitaRecorrente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ConsideraReservaEmergencia")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataTermino")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DiaRecebimento")
                        .HasColumnType("int");

                    b.Property<bool>("EhSalario")
                        .HasColumnType("bit");

                    b.Property<Guid>("IdContaFinanceira")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Natureza")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ValorPrevisto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdContaFinanceira");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "Ativa")
                        .HasDatabaseName("IX_ReceitaRecorrente_UsuarioId_Ativa");

                    b.HasIndex("UsuarioId", "DataInicio", "DataTermino")
                        .HasDatabaseName("IX_ReceitaRecorrente_UsuarioId_Periodo");

                    b.ToTable("tbReceitaRecorrente", (string)null);
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.ReceitaRecorrenteOcorrencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinalizadaEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("date");

                    b.Property<Guid?>("ReceitaConfirmadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReceitaRecorrenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReceitaConfirmadaId");

                    b.HasIndex("ReceitaRecorrenteId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "MesReferencia", "Status")
                        .HasDatabaseName("IX_ReceitaRecorrenteOcorrencia_Usuario_Mes_Status");

                    b.HasIndex("UsuarioId", "ReceitaRecorrenteId", "MesReferencia")
                        .IsUnique()
                        .HasDatabaseName("UX_ReceitaRecorrenteOcorrencia_Usuario_Recorrencia_Mes");

                    b.ToTable("tbReceitaRecorrenteOcorrencia", (string)null);
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("YourMoney.Domain.Entities.Categoria", "CategoriaPai")
                        .WithMany()
                        .HasForeignKey("CategoriaPaiId");

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.Despesa", b =>
                {
                    b.HasOne("YourMoney.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YourMoney.Domain.Entities.ContaFinanceira", "ContaFinanceira")
                        .WithMany()
                        .HasForeignKey("IdContaFinanceira")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("ContaFinanceira");
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.DespesaRecorrente", b =>
                {
                    b.HasOne("YourMoney.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YourMoney.Domain.Entities.ContaFinanceira", "ContaFinanceira")
                        .WithMany()
                        .HasForeignKey("IdContaFinanceira")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YourMoney.Domain.Entities.Categoria", "NaturezaDespesa")
                        .WithMany()
                        .HasForeignKey("IdNaturezaDespesa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YourMoney.Domain.Entities.Categoria", "TipoDespesa")
                        .WithMany()
                        .HasForeignKey("IdTipoDespesa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("ContaFinanceira");

                    b.Navigation("NaturezaDespesa");

                    b.Navigation("TipoDespesa");
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.DespesaRecorrenteOcorrencia", b =>
                {
                    b.HasOne("YourMoney.Domain.Entities.Despesa", "DespesaConfirmada")
                        .WithMany()
                        .HasForeignKey("DespesaConfirmadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YourMoney.Domain.Entities.DespesaRecorrente", "DespesaRecorrente")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("DespesaRecorrenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DespesaConfirmada");

                    b.Navigation("DespesaRecorrente");
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.Investimento", b =>
                {
                    b.HasOne("YourMoney.Domain.Entities.ReceitaRecorrente", "ReceitaRecorrente")
                        .WithMany()
                        .HasForeignKey("ReceitaRecorrenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReceitaRecorrente");
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.Meta", b =>
                {
                    b.HasOne("YourMoney.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.Receita", b =>
                {
                    b.HasOne("YourMoney.Domain.Entities.Despesa", "DespesaVinculada")
                        .WithMany()
                        .HasForeignKey("DespesaVinculadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YourMoney.Domain.Entities.ContaFinanceira", "ContaFinanceira")
                        .WithMany()
                        .HasForeignKey("IdContaFinanceira")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContaFinanceira");

                    b.Navigation("DespesaVinculada");
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.ReceitaRecorrente", b =>
                {
                    b.HasOne("YourMoney.Domain.Entities.ContaFinanceira", "ContaFinanceira")
                        .WithMany()
                        .HasForeignKey("IdContaFinanceira")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContaFinanceira");
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.ReceitaRecorrenteOcorrencia", b =>
                {
                    b.HasOne("YourMoney.Domain.Entities.Receita", "ReceitaConfirmada")
                        .WithMany()
                        .HasForeignKey("ReceitaConfirmadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YourMoney.Domain.Entities.ReceitaRecorrente", "ReceitaRecorrente")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("ReceitaRecorrenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReceitaConfirmada");

                    b.Navigation("ReceitaRecorrente");
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.DespesaRecorrente", b =>
                {
                    b.Navigation("Ocorrencias");
                });

            modelBuilder.Entity("YourMoney.Domain.Entities.ReceitaRecorrente", b =>
                {
                    b.Navigation("Ocorrencias");
                });
#pragma warning restore 612, 618
        }
    }
}
